### ISSUE TITLE
weights for network trained in paper

### ISSUE THREAD

**Issue by Andrew-Brown1** [kunhe/FastAP-metric-learning#2]
Hello, thanks for sharing your great work! 

Would you consider sharing the weights of your network that you used to achieve state-of-the-art on SOP with me? I appreciate that one set of weights would not achieve the numbers in the paper as you used ensemble but that is OK :)

**Comment by fcakir** [comment]
Thanks. The trained models in which the results were derived in the paper are now released. Please check the Reproducibility section on the front readme page.
