### ISSUE TITLE
Results for CUB and CARS datasets

### ISSUE THREAD

**Issue by asanakoy** [kunhe/FastAP-metric-learning#3]
Hi,

Nice work!
Do you guys have any quantitative results for CUB200-2011 and CARS196 datasets?
Are there any limitations which doesn't allow to train FastAP on such small datasets?

**Comment by fcakir** [comment]
FastAP generally works well with few-shot learning datasets but there are no limitations to what types of datasets that can be used. 

Just as a caution, the mini-batches should be constructed in a way similar to the proposed sampling method in the paper.
